/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/core.ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build the local search catalog from context sources */
        post: operations["core.ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core.query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a query: its rows, and the SQL that produced them */
        post: operations["core.query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core.query.compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compile a query to SQL, without running it */
        post: operations["core.query.compile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core.query.validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a query: its diagnostics, without running it */
        post: operations["core.query.validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core.search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search the local catalog */
        post: operations["core.search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Show the repo's datasets, or a dataset in full: its models, fields and metrics
         * @description Show an object of the repo, read from its compiled AML: with no fqn, the repo and its datasets
         *     in outline; with a dataset's fqn, that dataset in full, as AQL can query it. Its interface, not
         *     its implementation: names, labels, types, roles and AQL definitions, never SQL or tables. The
         *     repo's files that do not compile come with it, as diagnostics.
         */
        post: operations["core.show"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core.status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report whether a warm server is running and its sidecars are healthy */
        post: operations["core.status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core.validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate the AML repo, optionally scoped to file globs */
        post: operations["core.validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core.version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Print the anfra version */
        post: operations["core.version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AQLDiagnostic: {
            /** Format: int64 */
            column?: number;
            /** Format: int64 */
            line?: number;
            message: string;
            severity: string;
        };
        CompileError: {
            /** Format: int64 */
            col?: number;
            filePath?: string;
            message: string;
            /** Format: int64 */
            row?: number;
        };
        CompiledQuery: {
            /** @description the AQL compiled: the query with its Query Input applied; absent for a SQL query */
            aql?: string;
            /** @description what each column of an explore query's answer will be; absent for other queries */
            columns?: components["schemas"]["ExploreColumn"][];
            sql: string;
        };
        ContextEntry: {
            params?: {
                [key: string]: unknown;
            };
            step: string;
            text: string;
        };
        /** @description Something went wrong on our side. */
        ErrorBodyInternalServerError: {
            /** @constant */
            code: "internal_server_error";
            context?: components["schemas"]["ContextEntry"][];
            message: string;
            request_id: string;
            /** @constant */
            scope: "server";
            /** @constant */
            status: 500;
        };
        /** @description The request is not valid. */
        ErrorBodyInvalidRequest: {
            /** @constant */
            code: "invalid_request";
            context?: components["schemas"]["ContextEntry"][];
            details?: components["schemas"]["Violations"];
            message: string;
            request_id: string;
            /** @constant */
            scope: "client";
            /** @constant */
            status: 400;
        };
        /** @description The query failed to run on its data source. */
        ErrorBodyQueryFailed: {
            /** @constant */
            code: "query_failed";
            context?: components["schemas"]["ContextEntry"][];
            message: string;
            request_id: string;
            /** @constant */
            scope: "server";
            /** @constant */
            status: 502;
        };
        /** @description The query is invalid. */
        ErrorBodyQueryInvalid: {
            /** @constant */
            code: "query_invalid";
            context?: components["schemas"]["ContextEntry"][];
            details?: components["schemas"]["QueryValidation"];
            message: string;
            request_id: string;
            /** @constant */
            scope: "user";
            /** @constant */
            status: 422;
        };
        /** @description A sidecar is unavailable. */
        ErrorBodySidecarUnavailable: {
            /** @constant */
            code: "sidecar_unavailable";
            context?: components["schemas"]["ContextEntry"][];
            message: string;
            request_id: string;
            /** @constant */
            scope: "server";
            /** @constant */
            status: 503;
        };
        /** @description Some of the input is not valid. */
        ErrorBodyValidationFailed: {
            /** @constant */
            code: "validation_failed";
            context?: components["schemas"]["ContextEntry"][];
            details?: components["schemas"]["Violations"];
            message: string;
            request_id: string;
            /** @constant */
            scope: "user";
            /** @constant */
            status: 422;
        };
        ExploreColumn: {
            /** @description a query-local expression, not a field the dataset defines */
            adhoc: boolean;
            /** @description an aggregated field's aggregation, such as sum or count distinct */
            aggregation?: string;
            /** @description the field it draws; for an adhoc column, its name */
            fieldName: string;
            isMeasure: boolean;
            label: string;
            /** @description the model of fieldName, as the dataset names it; absent for a dataset metric or an adhoc column */
            modelId?: string;
            /** @description the column's key, as in fields */
            name: string;
        };
        IngestInput: {
            /** @description optional context source key to ingest */
            source?: string;
        };
        NoInput: Record<string, never>;
        QueryCondition: {
            /** @description an AQL condition */
            expr: string;
        };
        QueryDateDrill: {
            /** @description model.field: a date field */
            field: string;
            /** @description the grain, such as month */
            grain: string;
        };
        QueryFilter: {
            /** @description the condition applies to this aggregate of field, such as sum */
            aggregation?: string;
            /** @description model.field for a dataset field, or the name of a dataset metric */
            field: string;
            /** @description the date unit of a relative operator, such as day */
            modifier?: string;
            /** @description the operator, such as is, contains, between, last */
            operator: string;
            /** @description the operator's values: strings, numbers or booleans; empty for an operator that takes none */
            values: unknown[];
        };
        QueryInput: {
            /** @description the data source a SQL query runs against */
            data_source?: string;
            /** @description the dataset an AQL query runs against */
            dataset?: string;
            /**
             * @description the language the query is written in
             * @default aql
             * @enum {string}
             */
            lang?: "aql" | "sql";
            /** @description the query */
            query: string;
        };
        QueryResult: {
            /** @description the AQL that ran: the query with its Query Input applied; absent for a SQL query */
            aql?: string;
            /** @description one per field of result, in order */
            columns: components["schemas"]["ExploreColumn"][];
            result: components["schemas"]["QueryRows"];
            sql: string;
        };
        QueryRows: {
            fields: string[];
            records: unknown[][];
        };
        QueryRunInput: {
            /** @description the data source a SQL query runs against */
            data_source?: string;
            /** @description the dataset an AQL query runs against */
            dataset?: string;
            /** @description the Query Input: filters, conditions, sorts and date drills applied to the AQL before it compiles */
            input?: components["schemas"]["QueryTransforms"];
            /**
             * @description the language the query is written in
             * @default aql
             * @enum {string}
             */
            lang?: "aql" | "sql";
            /**
             * Format: int64
             * @description the 1-based page of rows to answer; needs a page size
             */
            page?: number;
            /**
             * Format: int64
             * @description rows per page; alone, the first page
             */
            page_size?: number;
            /** @description the query */
            query: string;
            /** @description the IANA time zone relative dates and date truncation use, such as Asia/Ho_Chi_Minh */
            timezone?: string;
        };
        QuerySort: {
            /**
             * @description the direction
             * @enum {string}
             */
            direction: "asc" | "desc";
            /** @description a result column's name */
            field: string;
        };
        QueryTransforms: {
            /** @description AQL conditions ANDed with the query's own filters */
            conditions?: components["schemas"]["QueryCondition"][];
            /** @description date fields redrawn at another grain, their columns' names kept */
            dateDrills?: components["schemas"]["QueryDateDrill"][];
            /** @description conditions on fields, ANDed with the query's own filters */
            filters?: components["schemas"]["QueryFilter"][];
            /** @description sorts by result column, replacing the query's own */
            sorts?: components["schemas"]["QuerySort"][];
        };
        QueryValidation: {
            diagnostics: components["schemas"]["AQLDiagnostic"][];
            valid: boolean;
        };
        RepoValidation: {
            diagnostics: components["schemas"]["CompileError"][];
            reports: components["schemas"]["ValidationReport"][];
            valid: boolean;
        };
        ReportTrace: {
            kind: string;
            loc?: components["schemas"]["ReportTraceLoc"];
            name: string;
        };
        ReportTraceLoc: {
            /** Format: int64 */
            column?: number;
            filePath: string;
            /** Format: int64 */
            line?: number;
        };
        SearchInput: {
            /** @description search query */
            query?: string[];
        };
        ServerInfo: {
            instance_id: string;
            url: string;
            version: string;
        };
        ShowDataset: {
            description?: string;
            /** @description the dataset's fully qualified name, as AQL and the catalog name it */
            fqn: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "dataset";
            label?: string;
            /** @description the dataset's metrics; absent in outline */
            metrics?: components["schemas"]["ShowField"][];
            /** @description the models the dataset uses; absent in outline */
            models?: components["schemas"]["ShowModel"][];
            name: string;
        };
        ShowField: {
            /** @description a measure's aggregation, such as sum or count distinct; custom for a custom one */
            aggregation?: string;
            /** @description a dimension the dataset declares on one of its models */
            definedInDataset?: boolean;
            /** @description the definition of a field or metric written in AQL */
            definition?: string;
            description?: string;
            /** @description how a value displays, as the AML declares it */
            format?: unknown;
            /** @description the catalog's identity: <model fqn>.<name>, or <dataset fqn>.<name> for a dataset-level field or a metric */
            fqn: string;
            hidden: boolean;
            label?: string;
            /** @description AQL writes <model fqn>.<name>; a metric, its name alone */
            name: string;
            /** @enum {string} */
            role: "dimension" | "measure" | "param" | "metric";
            /** @description the compiled data type, such as number, text, date, datetime, truefalse */
            type: string;
        };
        ShowInput: {
            /** @description the fqn of the object to show; absent, the repo */
            fqn?: string;
            /**
             * @description the catalog's entity type of fqn; aml.dataset is the only one for now
             * @default aml.dataset
             * @enum {string}
             */
            type?: "aml.dataset";
        };
        ShowModel: {
            description?: string;
            fields: components["schemas"]["ShowField"][];
            /** @description the model's fully qualified name: what AQL writes before a field */
            fqn: string;
            label?: string;
            name: string;
        };
        ShowRepo: {
            /** @description the repo's datasets, in outline */
            datasets: components["schemas"]["ShowDataset"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "repo";
        };
        ShowResult: {
            /** @description the repo's files that do not compile; empty, what is shown is complete */
            diagnostics: components["schemas"]["CompileError"][];
            /** @description the object shown, by kind; a client must accept a kind it does not know */
            object: components["schemas"]["ShowRepo"] | components["schemas"]["ShowDataset"];
        };
        SidecarHealth: {
            "canal-query": string;
            node: string;
        };
        StatusResult: {
            server?: components["schemas"]["ServerInfo"];
            sidecars?: components["schemas"]["SidecarHealth"];
            /** @enum {string} */
            state: "healthy" | "degraded" | "not_running";
        };
        ValidateInput: {
            /** @description optional file globs; report only diagnostics for matching files */
            globs?: string[];
        };
        ValidationReport: {
            code?: unknown;
            filePath: string;
            fqn: string;
            message: string;
            severity: string;
            trace?: components["schemas"]["ReportTrace"][];
            type: string;
            validator: string;
        };
        VersionResult: {
            version: string;
        };
        Violation: {
            code: string;
            field: string;
            message: string;
        };
        Violations: {
            violations: components["schemas"]["Violation"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "core.ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInvalidRequest"];
                    };
                };
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyValidationFailed"];
                    };
                };
            };
            /** @description internal_server_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInternalServerError"];
                    };
                };
            };
            /** @description sidecar_unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodySidecarUnavailable"];
                    };
                };
            };
        };
    };
    "core.query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRunInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResult"];
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInvalidRequest"];
                    };
                };
            };
            /** @description validation_failed, query_invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyValidationFailed"] | components["schemas"]["ErrorBodyQueryInvalid"];
                    };
                };
            };
            /** @description internal_server_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInternalServerError"];
                    };
                };
            };
            /** @description query_failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyQueryFailed"];
                    };
                };
            };
            /** @description sidecar_unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodySidecarUnavailable"];
                    };
                };
            };
        };
    };
    "core.query.compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRunInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompiledQuery"];
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInvalidRequest"];
                    };
                };
            };
            /** @description validation_failed, query_invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyValidationFailed"] | components["schemas"]["ErrorBodyQueryInvalid"];
                    };
                };
            };
            /** @description internal_server_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInternalServerError"];
                    };
                };
            };
            /** @description sidecar_unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodySidecarUnavailable"];
                    };
                };
            };
        };
    };
    "core.query.validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryValidation"];
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInvalidRequest"];
                    };
                };
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyValidationFailed"];
                    };
                };
            };
            /** @description internal_server_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInternalServerError"];
                    };
                };
            };
            /** @description sidecar_unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodySidecarUnavailable"];
                    };
                };
            };
        };
    };
    "core.search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInvalidRequest"];
                    };
                };
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyValidationFailed"];
                    };
                };
            };
            /** @description internal_server_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInternalServerError"];
                    };
                };
            };
            /** @description sidecar_unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodySidecarUnavailable"];
                    };
                };
            };
        };
    };
    "core.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShowInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowResult"];
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInvalidRequest"];
                    };
                };
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyValidationFailed"];
                    };
                };
            };
            /** @description internal_server_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInternalServerError"];
                    };
                };
            };
            /** @description sidecar_unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodySidecarUnavailable"];
                    };
                };
            };
        };
    };
    "core.status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResult"];
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInvalidRequest"];
                    };
                };
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyValidationFailed"];
                    };
                };
            };
            /** @description internal_server_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInternalServerError"];
                    };
                };
            };
        };
    };
    "core.validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoValidation"];
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInvalidRequest"];
                    };
                };
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyValidationFailed"];
                    };
                };
            };
            /** @description internal_server_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInternalServerError"];
                    };
                };
            };
            /** @description sidecar_unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodySidecarUnavailable"];
                    };
                };
            };
        };
    };
    "core.version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResult"];
                };
            };
            /** @description invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInvalidRequest"];
                    };
                };
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyValidationFailed"];
                    };
                };
            };
            /** @description internal_server_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ErrorBodyInternalServerError"];
                    };
                };
            };
        };
    };
}
